baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Thoughts, ideas, notes to self'
theme = 'paper'

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  # twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  github = 'chrisbendel'                 # github.com/YOUR_GITHUB_ID
  # instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'chrisbendel'             # linkedin.com/in/YOUR_LINKEDIN_ID
  # mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  # rss = true                                # show rss icon

  # home page profile
  #avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  name = 'Chris Bendel'
  bio = 'Person with some hobbies including software, photography, dogs, and daoism'


  # misc
  # disableHLJS = true                        # disable highlight.js
  # disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  # gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  # graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  math = true                               # enable KaTeX math typesetting globally
